// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: location.sql

package postgres

import (
	"context"
)

const createDesa = `-- name: CreateDesa :exec
INSERT INTO desa (kecamatan_id, nama) VALUES ($1, $2)
`

type CreateDesaParams struct {
	KecamatanID int32  `json:"kecamatan_id"`
	Nama        string `json:"nama"`
}

func (q *Queries) CreateDesa(ctx context.Context, arg CreateDesaParams) error {
	_, err := q.db.ExecContext(ctx, createDesa, arg.KecamatanID, arg.Nama)
	return err
}

const createKabupaten = `-- name: CreateKabupaten :exec
INSERT INTO kabupaten (provinsi_id, nama) VALUES ($1, $2)
`

type CreateKabupatenParams struct {
	ProvinsiID int32  `json:"provinsi_id"`
	Nama       string `json:"nama"`
}

func (q *Queries) CreateKabupaten(ctx context.Context, arg CreateKabupatenParams) error {
	_, err := q.db.ExecContext(ctx, createKabupaten, arg.ProvinsiID, arg.Nama)
	return err
}

const createKecamatan = `-- name: CreateKecamatan :exec
INSERT INTO kecamatan (kabupaten_id, nama) VALUES ($1, $2)
`

type CreateKecamatanParams struct {
	KabupatenID int32  `json:"kabupaten_id"`
	Nama        string `json:"nama"`
}

func (q *Queries) CreateKecamatan(ctx context.Context, arg CreateKecamatanParams) error {
	_, err := q.db.ExecContext(ctx, createKecamatan, arg.KabupatenID, arg.Nama)
	return err
}

const createProvinsi = `-- name: CreateProvinsi :exec
INSERT INTO provinsi (nama) VALUES ($1)
`

func (q *Queries) CreateProvinsi(ctx context.Context, nama string) error {
	_, err := q.db.ExecContext(ctx, createProvinsi, nama)
	return err
}

const deleteDesa = `-- name: DeleteDesa :exec
DELETE FROM desa WHERE id = $1
`

func (q *Queries) DeleteDesa(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDesa, id)
	return err
}

const deleteKabupaten = `-- name: DeleteKabupaten :exec
DELETE FROM kabupaten WHERE id = $1
`

func (q *Queries) DeleteKabupaten(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteKabupaten, id)
	return err
}

const deleteKecamatan = `-- name: DeleteKecamatan :exec
DELETE FROM kecamatan WHERE id = $1
`

func (q *Queries) DeleteKecamatan(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteKecamatan, id)
	return err
}

const deleteProvinsi = `-- name: DeleteProvinsi :exec
DELETE FROM provinsi WHERE id = $1
`

func (q *Queries) DeleteProvinsi(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProvinsi, id)
	return err
}
