// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: monitoring.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createMonitoringTerdaftar = `-- name: CreateMonitoringTerdaftar :exec
INSERT INTO monitoring_terdaftar (id, tipe_sensor_id, lokasi_id, nama, keterangan) VALUES ($1, $2, $3, $4, $5)
`

type CreateMonitoringTerdaftarParams struct {
	ID           uuid.UUID `json:"id"`
	TipeSensorID int32     `json:"tipe_sensor_id"`
	LokasiID     int32     `json:"lokasi_id"`
	Nama         string    `json:"nama"`
	Keterangan   string    `json:"keterangan"`
}

func (q *Queries) CreateMonitoringTerdaftar(ctx context.Context, arg CreateMonitoringTerdaftarParams) error {
	_, err := q.db.ExecContext(ctx, createMonitoringTerdaftar,
		arg.ID,
		arg.TipeSensorID,
		arg.LokasiID,
		arg.Nama,
		arg.Keterangan,
	)
	return err
}

const createMonitoringValue = `-- name: CreateMonitoringValue :exec
INSERT INTO monitoring_data (monitoring_terdaftar, value) VALUES ($1, $2)
`

type CreateMonitoringValueParams struct {
	MonitoringTerdaftar uuid.UUID `json:"monitoring_terdaftar"`
	Value               float64   `json:"value"`
}

func (q *Queries) CreateMonitoringValue(ctx context.Context, arg CreateMonitoringValueParams) error {
	_, err := q.db.ExecContext(ctx, createMonitoringValue, arg.MonitoringTerdaftar, arg.Value)
	return err
}
