// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Desa struct {
	ID          int32  `json:"id"`
	KecamatanID int32  `json:"kecamatan_id"`
	Nama        string `json:"nama"`
}

type Kabupaten struct {
	ID         int32  `json:"id"`
	ProvinsiID int32  `json:"provinsi_id"`
	Nama       string `json:"nama"`
}

type Kecamatan struct {
	ID          int32  `json:"id"`
	KabupatenID int32  `json:"kabupaten_id"`
	Nama        string `json:"nama"`
}

type MonitoringDatum struct {
	ID                  int64     `json:"id"`
	MonitoringTerdaftar uuid.UUID `json:"monitoring_terdaftar"`
	Value               float64   `json:"value"`
	DibuatPada          time.Time `json:"dibuat_pada"`
}

type MonitoringTerdaftar struct {
	ID           uuid.UUID `json:"id"`
	TipeSensorID int32     `json:"tipe_sensor_id"`
	LokasiID     int32     `json:"lokasi_id"`
	Email        string    `json:"email"`
	Author       string    `json:"author"`
	Nama         string    `json:"nama"`
	Keterangan   string    `json:"keterangan"`
}

type Provinsi struct {
	ID   int32  `json:"id"`
	Nama string `json:"nama"`
}

type TipeSensor struct {
	ID     int32  `json:"id"`
	Tipe   string `json:"tipe"`
	Satuan string `json:"satuan"`
}
